#!/bin/bash

cd ESP8266
case "$1" in
  com)
  echo 'Opening com...'
  killall picocom
  picocom /dev/ttyUSB1 -b 115200
  break
  up)
  killall picocom
  echo 'Uploading boot.py...'
  ampy -p /dev/ttyUSB1 put boot.py
  if [ -f main.py ]; then
    echo 'Uploading main.py...'
    ampy -p /dev/ttyUSB1 put main.py
  fi
  break
esac
